### ISSUE TITLE
AddEnvs: array of added envs not working propely

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/scoby#132]
A registration that includes 

```yaml
      addEnvs:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: K_METRICS_CONFIG
        value: "{}"
      - name: K_LOGGING_CONFIG
        value: "{}"

```

renders

```YAML
  - env:
    - name: K_LOGGING_CONFIG
      value: '{}'
    - name: K_LOGGING_CONFIG
      value: '{}'
    - name: K_LOGGING_CONFIG
      value: '{}'
```
