### ISSUE TITLE
Render: Allow injecting end user envvars from spec

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/scoby#85]
Allow spec sections where end users 

```yaml
spec:
  singleEnvVar:
    name: foo
    value: bar
  many:
  - name: env1
    value: val1
  - name: env2
    valueFrom:
      ConfigMapKeyRef:
        ...
```
